### ISSUE TITLE
请教数据预处理的问题

### ISSUE THREAD

**Issue by tianylin98** [Rosenberg37/EntityDetection#1]
您好，在论文实验中用到的三组数据集中，据我所知CoNLL和GENIA都是包含POS tags的，但是weiboNER是没有的，请问您这里处理过程中，
- 前两个数据集用的是自带的POS tags吗？
- weiboNER中的POS tags是如何获取的呢？

**Comment by wenxueru** [comment]
- 前两个数据集用的是自带的
- weiboNER数据集的pos来自这个[仓库](https://github.com/cchen-nlp/weiboNER)，应该是用[the Stanford Log-linear Part-Of-Speech Tagger](https://nlp.stanford.edu/software/tagger.shtml)打的
